### PR TITLE
Use serde instead of rustc-serialize

### LINKED ISSUE #19: serde support
as a Cargo feature -- `json_serde!` macro? or just make `json!` emit serde stuff?

### PR DESCRIPTION
**Pull request by yberreby**
Closes #19 and #24.

Adding a cargo feature would add quite a lot of complexity, so I propose to replace `rustc-serialize` with `serde` completely.  I presume that's what you meant by "make json! emit serde stuff".

This is a **breaking change**, reflected by a bump in the _minor_ version number since this crate is still 0.x.x.

### CODE REVIEW

**Comment by tomjakubowski** [comment]
Wow! I'm on vacation-ish this week for Christmas but I'll see if I can find squirrel up some time to review and play with this. I'm excited!

**Comment by Ticki** [comment]
This is pretty cool.

**Comment by tomjakubowski** [comment]
Just a few things off the top of my head:

* Unless there's a real problem, please don't rename the README. I prefer the `.markdown` extension for silly reasons.
* Did you run rustfmt on code snippets you edited? I'm seeing some irrelevant indentation changes. I'd be happy to accept a "rustfmt the whole repo" as a separate PR, but otherwise please limit style changes if possible.
* Similarly, there are a few irrelevant re-orderings in the Cargo.toml (it's fine to add yourself as an author + the keyword changes are OK). Could you revert those?

I'd also prefer not to totally break (the billions of, I'm sure ;-)) existing users with this change. What do you think of making serde an opt-in feature for the crate, at least for the time being?

**Comment by yberreby** [comment]
@tomjakubowski I'll address your points one by one:

* Alright, reverting now. I prefer .md because it's pretty much the _de facto_ standard nowadays, but you're the owner :)
* Yes, I have rustfmt set up to run automatically on save with [rust.vim](https://github.com/rust-lang/rust.vim), as I think it's good practice for projects to conform to the official Rust style, especially since rustfmt is now semi-official, since it landed in rust-lang-nursery. I'm sorry for having pushed style changes mixed with semantic changes, and I understand the inconvenience. But are you really sure you want me to redo my changes with rustfmt disabled, and _then_ rustfmt the repo? It's cleaner, sure, but it takes time.
* Those come from [cargo-edit's `cargo add`](https://github.com/killercup/cargo-edit). It's way more convenient than manually editing the Cargo.toml when developing, but, as you wish. I'll revert those when I can spare some time, which should be next Sunday (studies, you see).

I think aiming for minimum breakage is wise, of course. It _is_ possible to make serde opt-in, and it could be the better thing if you can spare the time to do it right, that is, avoid code duplication between the two macros. I don't have that time for now, which is why my PR is more modest.

Switching over to serde entirely shouldn't cause too much breakage, though, since existing users will still be able to use the 0.2.x series seamlessly as long as they use semver-compatible bounds, a best practice.

Now, if you can spare the time to do it 'right', then by all means do! My PR should save you some time in the process, so it will have been useful :)

**Comment by tomjakubowski** [comment]
> But are you really sure you want me to redo my changes with rustfmt disabled, and then rustfmt the repo? It's cleaner, sure, but it takes time.

That's fine.

> Those come from cargo-edit's cargo add. It's way more convenient than manually editing the Cargo.toml when developing, but, as you wish. I'll see what I can do about that when I can spare some time, which should not be before next Sunday (studies, you see).

Don't worry about it! I didn't realize.

**Comment by tomjakubowski** [comment]
I've got some time to spare now, I'll land this on a feature branch and finish up the work. Thanks for the PR!

**Comment by tomjakubowski** [comment]
Landed on master behind a feature flag.  See https://github.com/tomjakubowski/json_macros/commit/46fef6b740fa79f4acb409e66b68ed5d303b67d4

I'll cut a release shortly. Thanks again!

**Pull request merged**
