### PR TITLE
Update parse_expr() calls as per changes in libsyntax.

### PR DESCRIPTION
**Pull request by zsiciarz**
Same story again, the related changes are in
rust-lang/rust@44d8abcc0f372dbc7ad58f312303d2e59612dec9

### CODE REVIEW

**Comment by zsiciarz** [comment]
The last commit includes also a change to the plugin API location.

**Comment by tomjakubowski** [comment]
Argh, sorry for the delay.  LGTM.

**Comment by tomjakubowski** [comment]
Released to crates.io as v0.2.6. Thanks!

**Comment by tomjakubowski** [comment]
Oops, didn't release to crates.io -- which is a good thing because master doesn't compile. Looking into it.

**Comment by tomjakubowski** [comment]
Released, for real this time: https://crates.io/crates/json_macros/0.2.6

**Pull request merged**
