### PR TITLE
Update to latest rustc

### PR DESCRIPTION
**Pull request by zsiciarz**
Macro reform is in effect now. The code compiles, although I get weird
linker errors with undefined references to functions from
rustc-serialize.

### CODE REVIEW

**Comment by pzol** [comment]
That seems to be a compiler bug @yurume on IRC suggested to file an isolated error report, but I couldn't isolate that... seems to work fine otherwiese

**Comment by tomjakubowski** [comment]
Merged but not released. I'd like to be able to narrow down this compiler bug and report it at least first.

**Comment by tomjakubowski** [comment]
I suspect that the plugin is getting linked to one `rustc-serialize` crate (possibly the one that ships with `rustc`) and the end products (examples, tests) a different one (the one built by Cargo).

**Comment by tomjakubowski** [comment]
For posterity:

```
[tom@elbridge json_macros]$ cargo run --verbose --example kitchen-sink
   Compiling rustc-serialize v0.2.7
     Running `rustc /home/tom/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-serialize-0.2.7/src/lib.rs --crate-name rustc-serialize --crate-type lib -g -C metadata=13c851f4817562e4 -C extra-filename=-13c851f4817562e4 --out-dir /home/tom/code/rust/json_macros/target/deps --emit=dep-info,link -L /home/tom/code/rust/json_macros/target/deps -L /home/tom/code/rust/json_macros/target/deps -Awarnings`
   Compiling json_macros v0.1.2 (file:///home/tom/code/rust/json_macros)
     Running `rustc src/macro.rs --crate-name json_macros --crate-type dylib -C prefer-dynamic -g -C metadata=0df5b68946b8b044 -C extra-filename=-0df5b68946b8b044 --out-dir /home/tom/code/rust/json_macros/target --emit=dep-info,link -L /home/tom/code/rust/json_macros/target -L /home/tom/code/rust/json_macros/target/deps --extern rustc-serialize=/home/tom/code/rust/json_macros/target/deps/librustc-serialize-13c851f4817562e4.rlib`
     Running `rustc src/macro.rs --crate-name json_macros --crate-type dylib -C prefer-dynamic -g --test -C metadata=4b473d2ec10e31c7 -C extra-filename=-4b473d2ec10e31c7 --out-dir /home/tom/code/rust/json_macros/target --emit=dep-info,link -L /home/tom/code/rust/json_macros/target -L /home/tom/code/rust/json_macros/target/deps --extern rustc-serialize=/home/tom/code/rust/json_macros/target/deps/librustc-serialize-13c851f4817562e4.rlib`
     Running `rustc examples/kitchen_sink.rs --crate-name kitchen-sink --crate-type bin -g --out-dir /home/tom/code/rust/json_macros/target/examples --emit=dep-info,link -L /home/tom/code/rust/json_macros/target -L /home/tom/code/rust/json_macros/target/deps --extern rustc-serialize=/home/tom/code/rust/json_macros/target/deps/librustc-serialize-13c851f4817562e4.rlib`
     Running `rustc tests/tests.rs --crate-name tests --crate-type bin -g --test -C metadata=aeeec77130b1bba4 -C extra-filename=-aeeec77130b1bba4 --out-dir /home/tom/code/rust/json_macros/target --emit=dep-info,link -L /home/tom/code/rust/json_macros/target -L /home/tom/code/rust/json_macros/target/deps --extern rustc-serialize=/home/tom/code/rust/json_macros/target/deps/librustc-serialize-13c851f4817562e4.rlib --extern json_macros=/home/tom/code/rust/json_macros/target/libjson_macros-0df5b68946b8b044.so`
error: linking with `cc` failed: exit code: 1
note: cc '-Wl,--as-needed' '-m64' '-L' '/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib' '-o' '/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4' '/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o' '-Wl,--whole-archive' '-lmorestack' '-Wl,--no-whole-archive' '-Wl,--gc-sections' '-pie' '-nodefaultlibs' '-L' '/home/tom/code/rust/json_macros/target' '-ljson_macros-0df5b68946b8b044' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-ltest-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lrustc-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lrustc_back-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lsyntax-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lfmt_macros-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lgraphviz-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lflate-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-larena-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lgetopts-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lterm-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lrbml-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lserialize-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-llog-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lregex-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lrustc_llvm-4e7c5e5c' '-L' '/usr/lib/rustlib/x86_64-unknown-linux-gnu/lib' '-lstd-4e7c5e5c' '-L' '/home/tom/code/rust/json_macros/target' '-L' '/home/tom/code/rust/json_macros/target/deps' '-L' '/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib' '-L' '/home/tom/code/rust/json_macros/.rust/lib64/x86_64-unknown-linux-gnu' '-L' '/home/tom/code/rust/json_macros/lib64/x86_64-unknown-linux-gnu' '-Wl,--whole-archive' '-Wl,-Bstatic' '-Wl,--no-whole-archive' '-Wl,-Bdynamic' '-lpthread' '-ldl' '-lm' '-lstdc++' '-ldl' '-lpthread' '-lrt' '-lgcc_s' '-lpthread' '-lc' '-lm' '-lcompiler-rt'
note: /home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `tests::test_string_lit':
/home/tom/code/rust/json_macros/<std macros>:12: undefined reference to `json::Json::as_string::h911fcc7fe4f47eb48Ng'
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `tests::test_num_lit':
/home/tom/code/rust/json_macros/<std macros>:17: undefined reference to `json::Json::as_i64::h43898aae1c3bff61FPg'
/home/tom/code/rust/json_macros/<std macros>:18: undefined reference to `json::Json::as_f64::h47258dbd69af92cctQg'
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `tests::test_null_lit':
/home/tom/code/rust/json_macros/tests/tests.rs:23: undefined reference to `json::Json::is_null::h8979b3f3e15b99e9sRg'
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `tests::test_bool_lit':
/home/tom/code/rust/json_macros/<std macros>:28: undefined reference to `json::Json::as_boolean::hdb8fe78786ea19458Qg'
/home/tom/code/rust/json_macros/<std macros>:29: undefined reference to `json::Json::as_boolean::hdb8fe78786ea19458Qg'
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `tests::test_array_lit':
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/<std macros>:36: undefined reference to `json::string..String.ToJson::to_json::h2c9e7050ad84fcb8zfj'
/home/tom/code/rust/json_macros/<std macros>:37: undefined reference to `json::string..String.ToJson::to_json::h2c9e7050ad84fcb8zfj'
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/<std macros>:40: undefined reference to `json::string..String.ToJson::to_json::h2c9e7050ad84fcb8zfj'
/home/tom/code/rust/json_macros/<std macros>:41: undefined reference to `json::string..String.ToJson::to_json::h2c9e7050ad84fcb8zfj'
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `json::Vec$LT$A$GT$.ToJson::to_json::unboxed_closure.3113':
tests.0.rs:(.text._ZN4json19Vec$LT$A$GT$.ToJson7to_json20unboxed_closure.3113E+0x4d): undefined reference to `json::Json.ToJson::to_json::haa169468e5f377abOdj'
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `tests::test_object_lit':
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/<std macros>:9: undefined reference to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe'
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o:/home/tom/code/rust/json_macros/<std macros>:9: more undefined references to `json::Json...std..fmt..Show::fmt::h2f720fc5767c9901bbe' follow
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `tests::test_expr_insertion':
/home/tom/code/rust/json_macros/<quote expansion>:7: undefined reference to `json::string..String.ToJson::to_json::h2c9e7050ad84fcb8zfj'
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `tests::test_expr_insertion':
/home/tom/code/rust/json_macros/<std macros>:79: undefined reference to `json::Json::find::h9e4c64e5cfccb5f4sKg'
/home/tom/code/rust/json_macros/target/tests-aeeec77130b1bba4.o: In function `fnfn':
/home/tom/code/rust/json_macros/tests/tests.rs:79: undefined reference to `json::Json::as_string::h911fcc7fe4f47eb48Ng'
collect2: error: ld returned 1 exit status

error: aborting due to previous error
Could not compile `json_macros`.

Caused by:
  Process didn't exit successfully: `rustc tests/tests.rs --crate-name tests --crate-type bin -g --test -C metadata=aeeec77130b1bba4 -C extra-filename=-aeeec77130b1bba4 --out-dir /home/tom/code/rust/json_macros/target --emit=dep-info,link -L /home/tom/code/rust/json_macros/target -L /home/tom/code/rust/json_macros/target/deps --extern rustc-serialize=/home/tom/code/rust/json_macros/target/deps/librustc-serialize-13c851f4817562e4.rlib --extern json_macros=/home/tom/code/rust/json_macros/target/libjson_macros-0df5b68946b8b044.so` (status=101)
```

**Comment by tomjakubowski** [comment]
Finally tracked down the problem. I guess `#[no_link]` is important after all!

https://github.com/rust-lang/cargo/issues/1155

**Comment by pzol** [comment]
\o/

**Pull request merged**
